/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package internalversion

import (
	batch "github.com/the-redback/apiserver-builded/pkg/apis/batch"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MyKindLister helps list MyKinds.
type MyKindLister interface {
	// List lists all MyKinds in the indexer.
	List(selector labels.Selector) (ret []*batch.MyKind, err error)
	// MyKinds returns an object that can list and get MyKinds.
	MyKinds(namespace string) MyKindNamespaceLister
	MyKindListerExpansion
}

// myKindLister implements the MyKindLister interface.
type myKindLister struct {
	indexer cache.Indexer
}

// NewMyKindLister returns a new MyKindLister.
func NewMyKindLister(indexer cache.Indexer) MyKindLister {
	return &myKindLister{indexer: indexer}
}

// List lists all MyKinds in the indexer.
func (s *myKindLister) List(selector labels.Selector) (ret []*batch.MyKind, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*batch.MyKind))
	})
	return ret, err
}

// MyKinds returns an object that can list and get MyKinds.
func (s *myKindLister) MyKinds(namespace string) MyKindNamespaceLister {
	return myKindNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MyKindNamespaceLister helps list and get MyKinds.
type MyKindNamespaceLister interface {
	// List lists all MyKinds in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*batch.MyKind, err error)
	// Get retrieves the MyKind from the indexer for a given namespace and name.
	Get(name string) (*batch.MyKind, error)
	MyKindNamespaceListerExpansion
}

// myKindNamespaceLister implements the MyKindNamespaceLister
// interface.
type myKindNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MyKinds in the indexer for a given namespace.
func (s myKindNamespaceLister) List(selector labels.Selector) (ret []*batch.MyKind, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*batch.MyKind))
	})
	return ret, err
}

// Get retrieves the MyKind from the indexer for a given namespace and name.
func (s myKindNamespaceLister) Get(name string) (*batch.MyKind, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(batch.Resource("mykind"), name)
	}
	return obj.(*batch.MyKind), nil
}
