/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package internalversion

import (
	batch "github.com/the-redback/apiserver-builded/pkg/apis/batch"
	internalclientset "github.com/the-redback/apiserver-builded/pkg/client/clientset_generated/internalclientset"
	internalinterfaces "github.com/the-redback/apiserver-builded/pkg/client/informers_generated/internalversion/internalinterfaces"
	internalversion "github.com/the-redback/apiserver-builded/pkg/client/listers_generated/batch/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// MyKindInformer provides access to a shared informer and lister for
// MyKinds.
type MyKindInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.MyKindLister
}

type myKindInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMyKindInformer constructs a new informer for MyKind type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMyKindInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMyKindInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMyKindInformer constructs a new informer for MyKind type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMyKindInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Batch().MyKinds(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Batch().MyKinds(namespace).Watch(options)
			},
		},
		&batch.MyKind{},
		resyncPeriod,
		indexers,
	)
}

func (f *myKindInformer) defaultInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMyKindInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *myKindInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&batch.MyKind{}, f.defaultInformer)
}

func (f *myKindInformer) Lister() internalversion.MyKindLister {
	return internalversion.NewMyKindLister(f.Informer().GetIndexer())
}
