// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1

import (
	batch "github.com/the-redback/apiserver-builded/pkg/apis/batch"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1_MyKind_To_batch_MyKind,
		Convert_batch_MyKind_To_v1_MyKind,
		Convert_v1_MyKindList_To_batch_MyKindList,
		Convert_batch_MyKindList_To_v1_MyKindList,
		Convert_v1_MyKindSpec_To_batch_MyKindSpec,
		Convert_batch_MyKindSpec_To_v1_MyKindSpec,
		Convert_v1_MyKindStatus_To_batch_MyKindStatus,
		Convert_batch_MyKindStatus_To_v1_MyKindStatus,
		Convert_v1_MyKindStatusStrategy_To_batch_MyKindStatusStrategy,
		Convert_batch_MyKindStatusStrategy_To_v1_MyKindStatusStrategy,
		Convert_v1_MyKindStrategy_To_batch_MyKindStrategy,
		Convert_batch_MyKindStrategy_To_v1_MyKindStrategy,
	)
}

func autoConvert_v1_MyKind_To_batch_MyKind(in *MyKind, out *batch.MyKind, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_MyKindSpec_To_batch_MyKindSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_MyKindStatus_To_batch_MyKindStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_MyKind_To_batch_MyKind is an autogenerated conversion function.
func Convert_v1_MyKind_To_batch_MyKind(in *MyKind, out *batch.MyKind, s conversion.Scope) error {
	return autoConvert_v1_MyKind_To_batch_MyKind(in, out, s)
}

func autoConvert_batch_MyKind_To_v1_MyKind(in *batch.MyKind, out *MyKind, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_batch_MyKindSpec_To_v1_MyKindSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_batch_MyKindStatus_To_v1_MyKindStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_batch_MyKind_To_v1_MyKind is an autogenerated conversion function.
func Convert_batch_MyKind_To_v1_MyKind(in *batch.MyKind, out *MyKind, s conversion.Scope) error {
	return autoConvert_batch_MyKind_To_v1_MyKind(in, out, s)
}

func autoConvert_v1_MyKindList_To_batch_MyKindList(in *MyKindList, out *batch.MyKindList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]batch.MyKind)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_MyKindList_To_batch_MyKindList is an autogenerated conversion function.
func Convert_v1_MyKindList_To_batch_MyKindList(in *MyKindList, out *batch.MyKindList, s conversion.Scope) error {
	return autoConvert_v1_MyKindList_To_batch_MyKindList(in, out, s)
}

func autoConvert_batch_MyKindList_To_v1_MyKindList(in *batch.MyKindList, out *MyKindList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MyKind)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_batch_MyKindList_To_v1_MyKindList is an autogenerated conversion function.
func Convert_batch_MyKindList_To_v1_MyKindList(in *batch.MyKindList, out *MyKindList, s conversion.Scope) error {
	return autoConvert_batch_MyKindList_To_v1_MyKindList(in, out, s)
}

func autoConvert_v1_MyKindSpec_To_batch_MyKindSpec(in *MyKindSpec, out *batch.MyKindSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1_MyKindSpec_To_batch_MyKindSpec is an autogenerated conversion function.
func Convert_v1_MyKindSpec_To_batch_MyKindSpec(in *MyKindSpec, out *batch.MyKindSpec, s conversion.Scope) error {
	return autoConvert_v1_MyKindSpec_To_batch_MyKindSpec(in, out, s)
}

func autoConvert_batch_MyKindSpec_To_v1_MyKindSpec(in *batch.MyKindSpec, out *MyKindSpec, s conversion.Scope) error {
	return nil
}

// Convert_batch_MyKindSpec_To_v1_MyKindSpec is an autogenerated conversion function.
func Convert_batch_MyKindSpec_To_v1_MyKindSpec(in *batch.MyKindSpec, out *MyKindSpec, s conversion.Scope) error {
	return autoConvert_batch_MyKindSpec_To_v1_MyKindSpec(in, out, s)
}

func autoConvert_v1_MyKindStatus_To_batch_MyKindStatus(in *MyKindStatus, out *batch.MyKindStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_MyKindStatus_To_batch_MyKindStatus is an autogenerated conversion function.
func Convert_v1_MyKindStatus_To_batch_MyKindStatus(in *MyKindStatus, out *batch.MyKindStatus, s conversion.Scope) error {
	return autoConvert_v1_MyKindStatus_To_batch_MyKindStatus(in, out, s)
}

func autoConvert_batch_MyKindStatus_To_v1_MyKindStatus(in *batch.MyKindStatus, out *MyKindStatus, s conversion.Scope) error {
	return nil
}

// Convert_batch_MyKindStatus_To_v1_MyKindStatus is an autogenerated conversion function.
func Convert_batch_MyKindStatus_To_v1_MyKindStatus(in *batch.MyKindStatus, out *MyKindStatus, s conversion.Scope) error {
	return autoConvert_batch_MyKindStatus_To_v1_MyKindStatus(in, out, s)
}

func autoConvert_v1_MyKindStatusStrategy_To_batch_MyKindStatusStrategy(in *MyKindStatusStrategy, out *batch.MyKindStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1_MyKindStatusStrategy_To_batch_MyKindStatusStrategy is an autogenerated conversion function.
func Convert_v1_MyKindStatusStrategy_To_batch_MyKindStatusStrategy(in *MyKindStatusStrategy, out *batch.MyKindStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1_MyKindStatusStrategy_To_batch_MyKindStatusStrategy(in, out, s)
}

func autoConvert_batch_MyKindStatusStrategy_To_v1_MyKindStatusStrategy(in *batch.MyKindStatusStrategy, out *MyKindStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_batch_MyKindStatusStrategy_To_v1_MyKindStatusStrategy is an autogenerated conversion function.
func Convert_batch_MyKindStatusStrategy_To_v1_MyKindStatusStrategy(in *batch.MyKindStatusStrategy, out *MyKindStatusStrategy, s conversion.Scope) error {
	return autoConvert_batch_MyKindStatusStrategy_To_v1_MyKindStatusStrategy(in, out, s)
}

func autoConvert_v1_MyKindStrategy_To_batch_MyKindStrategy(in *MyKindStrategy, out *batch.MyKindStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1_MyKindStrategy_To_batch_MyKindStrategy is an autogenerated conversion function.
func Convert_v1_MyKindStrategy_To_batch_MyKindStrategy(in *MyKindStrategy, out *batch.MyKindStrategy, s conversion.Scope) error {
	return autoConvert_v1_MyKindStrategy_To_batch_MyKindStrategy(in, out, s)
}

func autoConvert_batch_MyKindStrategy_To_v1_MyKindStrategy(in *batch.MyKindStrategy, out *MyKindStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_batch_MyKindStrategy_To_v1_MyKindStrategy is an autogenerated conversion function.
func Convert_batch_MyKindStrategy_To_v1_MyKindStrategy(in *batch.MyKindStrategy, out *MyKindStrategy, s conversion.Scope) error {
	return autoConvert_batch_MyKindStrategy_To_v1_MyKindStrategy(in, out, s)
}
